# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR3rv5nK3x01pW6vCixj7iO0-9_MK65H
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1) Load data into a DataFrame (tabular CSV from Our World in Data)
url = "https://ourworldindata.org/grapher/coffee-production-by-region.csv"
df = pd.read_csv(url)

print("Raw shape:", df.shape)
display(df.head())

# 2) Save the raw data file (this creates a CSV in your Colab environment)
raw_path = "coffee_production_raw.csv"
df.to_csv(raw_path, index=False)
print("Saved raw data to:", raw_path)

# If you want to download it to your computer:
from google.colab import files
files.download(raw_path)

# 3) Basic cleaning / preprocessing
# Standardize column names
df = df.rename(columns={"Entity": "entity", "Year": "year", "Coffee bean production (tonnes)": "production_tonnes"})

# Drop missing values and fix data types
df = df.dropna(subset=["entity", "year", "production_tonnes"]).copy()
df["year"] = df["year"].astype(int)
df["production_tonnes"] = pd.to_numeric(df["production_tonnes"], errors="coerce")
df = df.dropna(subset=["production_tonnes"])

print("Cleaned shape:", df.shape)
display(df.head())

# 4) Visualization (example: trend for a few major regions + World if available)
# Pick a few entities that usually exist in this file
candidates = ["World", "South America", "Africa", "Asia", "North America", "Europe"]
available = [c for c in candidates if c in set(df["entity"])]

# If "World" isn't present, fall back to the top entities by latest year
if not available:
    latest_year = df["year"].max()
    top_entities = (
        df[df["year"] == latest_year]
        .sort_values("production_tonnes", ascending=False)
        .head(5)["entity"]
        .tolist()
    )
    available = top_entities

plot_df = df[df["entity"].isin(available)].pivot(index="year", columns="entity", values="production_tonnes").sort_index()

plt.figure()
plt.plot(plot_df.index, plot_df.values)
plt.title("Coffee production over time (tonnes)")
plt.xlabel("Year")
plt.ylabel("Production (tonnes)")
plt.legend(plot_df.columns, loc="best")
plt.show()